### ISSUE TITLE
CIパイプライン構築

### ISSUE THREAD

**Issue by DeliciousKokas** [DeliciousKokas/myapp#24]
## 概要
- CIパイプラインで環境テストを自動化する

## 受け入れ基準
- CIにより、環境テストが実施できること

**Comment by DeliciousKokas** [comment]
rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.

**Comment by DeliciousKokas** [comment]
言語イメージのバリアント
`-node-browsers`
https://circleci.com/docs/ja/2.0/circleci-images/#%E8%A8%80%E8%AA%9E%E3%82%A4%E3%83%A1%E3%83%BC%E3%82%B8%E3%81%AE%E3%83%90%E3%83%AA%E3%82%A2%E3%83%B3%E3%83%88

**Comment by DeliciousKokas** [comment]
Unknown MySQL server host 'db' (-2)
Couldn't create 'myapp_test' database. Please check your configuration.
rake aborted!
Mysql2::Error::ConnectionError: Unknown MySQL server host 'db' (-2)

**Comment by DeliciousKokas** [comment]
https://qiita.com/toyoken/items/16f3b6df06bbe393e644

**Comment by DeliciousKokas** [comment]
Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused")
Couldn't create 'myapp_test' database. Please check your configuration.
rake aborted!

**Comment by DeliciousKokas** [comment]
テスト結果保存
```
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
```

**Comment by DeliciousKokas** [comment]
### CircleCIエラー再発
```
Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused")
Couldn't create 'myapp_test' database. Please check your configuration.
rake aborted!
```

### DB起動まで遅延
https://qiita.com/t-izaki/items/c6ef3239176f9c6697f2
```
steps:
  - run:
      name: Wait for DB
      command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
```
