### ISSUE TITLE
rspec_modelプロトタイプテスト作成

### ISSUE THREAD

**Issue by DeliciousKokas** [DeliciousKokas/myapp#7]
## 概要
- アプリケーションテストのプロトタイプ作成

## 受け入れ基準
- 全てのmodelにテストが実装されること

**Comment by DeliciousKokas** [comment]
Spring : 実行したアプリケーションをバックグランドで走らせる(２回目以降の速度向上)
https://github.com/rails/spring

rspecをspringに含ませるための記載(テスト実行時間が長くなったら利用検討)
`gem 'spring-commands-rspec'`

**Comment by DeliciousKokas** [comment]
modelテスト失敗時にエラーが表示されるのか確認したい
→　Issue化

**Comment by DeliciousKokas** [comment]
User.nameのvaildatesなし
→ User modelに追記
`validates :name, presence: true, uniqueness: true, length: { in: 4..12 }`

**Comment by DeliciousKokas** [comment]
- devise既存のvaildates
The email is present, unique and its format is valid. 
Also tests presence of password, confirmation and length.
https://www.rubydoc.info/github/heartcombo/devise/master/Devise/Models/Validatable

- 英・数・記号を各1文字以上, かつ8~16文字
 ```
VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)(?=.*?[\W_])[!-~]+\z/i
 validates :password, presence: true, length: { in: 8..16 }, format: { with: VALID_PASSWORD_REGEX}
```
https://rakuda3desu.net/out-of-rakudas-rails-tutoria-password-validation/

**Comment by DeliciousKokas** [comment]
なぜか失敗する
```
  it "is invalid with a duplicate email address" do
    user_1 = FactoryBot.build(:user)
    user_2 = User.new(name:"test2", password:"test23452345!", email:user_1.email)
    expect(user_1).to be_valid
    user_2.valid?
    expect(user_2.errors[:email]).to include("has already been taken")
  end
```

```
  1) User is invalid with a duplicate email address
     Failure/Error: expect(user_2.errors[:email]).to include("has already been taken")
       expected [] to include "has already been taken"
     # ./spec/models/user_spec.rb:38:in `block (2 levels) in <main>'
```

**Comment by DeliciousKokas** [comment]
record.rbでエラー発生
```
  1) Record is valid with a start_time and user_id
     Failure/Error: record = FactoryBot.build(user_id:user.id)
     
     ArgumentError:
       Factory not registered: {:user_id=>38}
     # /usr/local/bundle/gems/factory_bot-4.10.0/lib/factory_bot/registry.rb:24:in `find'
     # /usr/local/bundle/gems/factory_bot-4.10.0/lib/factory_bot/decorator.rb:10:in `method_missing'
     # /usr/local/bundle/gems/factory_bot-4.10.0/lib/factory_bot.rb:100:in `factory_by_name'
     # /usr/local/bundle/gems/factory_bot-4.10.0/lib/factory_bot/factory_runner.rb:12:in `run'
     # /usr/local/bundle/gems/factory_bot-4.10.0/lib/factory_bot/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/models/record_spec.rb:6:in `block (2 levels) in <main>'
```
